/**
 * Stripe Webhook Receiver & Handler API Route
 * 
 * Destination / Target Webhook URL:
 * - Production: POST https://image-gen-saas-pi.vercel.app/api/webhooks/stripe
 * - Local Testing: POST http://localhost:3000/api/webhooks/stripe (via Stripe CLI `stripe listen`)
 * 
 * Purpose:
 * Listens for asynchronous payment events emitted by Stripe (e.g. `checkout.session.completed`).
 * Verifies cryptographic HMAC signature using STRIPE_WEBHOOK_SECRET, prevents duplicate
 * execution via idempotency checks, records Payment transactions in MongoDB, and grants
 * user credits atomically.
 * 
 * Header Required:
 * - stripe-signature: Signature header generated by Stripe for payload verification
 */

import { NextResponse } from "next/server";
import Stripe from "stripe";
import stripe from "@/lib/stripe/stripe";
import connectDB from "@/lib/db";
import { Payment, PaymentStatus } from "@/models/Payment";
import { User } from "@/models/User";

// Named constants for plan credit allocations
const PRO_PLAN_CREDITS = 500;
const MAX_PLAN_CREDITS = 2000;
const DEFAULT_CREDITS = 500;

// Credit mapping dictionary based on subscribed plan
const PLAN_CREDITS_MAP: Record<string, number> = {
  pro: PRO_PLAN_CREDITS,
  max: MAX_PLAN_CREDITS,
};

export const POST = async (req: Request) => {
  try {
    // Step 1: Read raw unparsed request body text (required for cryptographic signature verification)
    const bodyText = await req.text();
    const signature = req.headers.get("stripe-signature");
    const webhookSecret = process.env.STRIPE_WEBHOOK_SECRET;

    if (!signature || !webhookSecret) {
      console.error("[webhooks/stripe] Missing signature or STRIPE_WEBHOOK_SECRET");
      return NextResponse.json(
        { error: "Missing webhook configuration" },
        { status: 400 }
      );
    }

    let event: Stripe.Event;

    // Step 2: Verify Stripe cryptographic HMAC signature using constructEvent()
    try {
      event = stripe.webhooks.constructEvent(bodyText, signature, webhookSecret);
    } catch (err: any) {
      console.error("[webhooks/stripe] Signature verification failed:", err.message);
      return NextResponse.json(
        { error: `Webhook Error: ${err.message}` },
        { status: 400 }
      );
    }

    console.log("[webhooks/stripe] Verified event received:", { type: event.type, id: event.id });

    // Step 3: Handle `checkout.session.completed` event when payment succeeds
    if (event.type === "checkout.session.completed") {
      const session = event.data.object as Stripe.Checkout.Session;
      const userId = session.metadata?.userId || session.client_reference_id;
      const plan = session.metadata?.plan || "pro";

      if (!userId) {
        console.error("[webhooks/stripe] Missing userId in session metadata", { sessionId: session.id });
        return NextResponse.json({ received: true });
      }

      await connectDB();

      // Step 4: Idempotency Check — query MongoDB Payment collection to prevent double-crediting
      const existingPayment = await Payment.findOne({ providerSessionId: session.id });
      if (existingPayment) {
        console.log("[webhooks/stripe] Payment already processed for session:", session.id);
        return NextResponse.json({ received: true });
      }

      const creditsToAdd = PLAN_CREDITS_MAP[plan] || DEFAULT_CREDITS;
      const amountInDollars = session.amount_total ? session.amount_total / 100 : 0;

      // Step 5: Record transaction in MongoDB Payment model
      await Payment.create({
        userId,
        providerSessionId: session.id,
        provider: "stripe",
        amount: amountInDollars,
        currency: session.currency || "usd",
        plan,
        creditsAdded: creditsToAdd,
        status: PaymentStatus.COMPLETED,
      });

      // Extract Stripe Customer ID and Subscription ID if available
      const customerId = typeof session.customer === "string" ? session.customer : undefined;
      const subscriptionId = typeof session.subscription === "string" ? session.subscription : undefined;

      const updatePayload: Record<string, any> = {
        plan: plan,
      };

      if (customerId) {
        updatePayload.billingCustomerId = customerId;
      }
      if (subscriptionId) {
        updatePayload.billingSubscriptionId = subscriptionId;
      }

      // Step 6: Atomically increment user credits ($inc) and update plan ($set) in MongoDB
      await User.findByIdAndUpdate(userId, {
        $inc: { credits: creditsToAdd },
        $set: updatePayload,
      });

      console.log("[webhooks/stripe] Granted credits and updated user plan", {
        userId,
        creditsToAdd,
        plan,
        customerId,
        subscriptionId,
      });
    }

    // Return 200 OK to Stripe confirming successful receipt
    return NextResponse.json({ received: true });
  } catch (error: any) {
    console.error("[webhooks/stripe] Error processing webhook", error);
    return NextResponse.json(
      { error: error.message || "Internal server error" },
      { status: 500 }
    );
  }
};
